# Generated by Django 6.0 on 2026-01-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_reflection_schedule_remove_goal_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
