# Generated by Django 6.0 on 2026-01-31 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='note',
        ),
    ]
