# Generated by Django 6.0 on 2026-01-15 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_goal_journal_alter_todo_journal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='journal.journal')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
