# Generated by Django 6.0 on 2026-01-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_todo_end_time_remove_todo_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_done',
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
